### ISSUE TITLE
Profiler Set Purpose (description) missing on restore 

### ISSUE THREAD

**Issue by slusardi01** [delphix/masking-initializer#2]
Using a backup created via:
dlpx-masking-initializer -f lab_bkup -H labEngine -p 8282 -u delphixAPI -P  <insert_password>  -b -g -e -m -c

A restore does not populate the purpose column for a user created or Delphix created profiler set.   The word "false" is listed in the GUI after restore with -s option.  The base.json file shows the word "false" in the description parameter.

Update:  After manually fixing descriptions on profiler sets on our production engines, any subsequent restores also get reset to "false".

**Comment by slusardi01** [comment]
Can you please clarify if this is a bug with the API or the initializer script ?

**Comment by bpg130** [comment]
This is a bug in the initializer script and will be fixed in the next release!
