### ISSUE TITLE
Error loading specific connector from missing profile set ID#

### ISSUE THREAD

**Issue by slusardi01** [delphix/masking-initializer#5]
Engine 1 has several user created algorithms, domains, profiler expression, profiler sets, and envs.

Engine 2 has a few user created algorithms on it, the two delphix profile sets, and one user created profiler set that is not resident on engine 1.

Engine 1 is backed up using these options:  -b -g -e -m -c

BASE.json edited to bring over just one env for testing.
Restore to Engine 2 is executed using the -s -l DEBUG option.

Error message:
10:58:05.189 [main] DEBUG com.delphix.masking.initializer.maskingApi.endpointCaller.ApiCallDriver - Body: {
  "profileJobId": 94,
  "jobName": "BENDB-Profile-HSA",
  "profileSetId": 3,
  "rulesetId": 3,
  "createdBy": "delphix_admin",
  "createdTime": "2018-01-17T19:51:03.178+0000",
  "email": "",
  "feedbackSize": 50000,
  "jobDescription": "",
  "maxMemory": 16382,
  "minMemory": 16382,
  "multiTenant": false,
  "numInputStreams": 20
}
10:58:05.205 [main] DEBUG com.delphix.masking.initializer.maskingApi.endpointCaller.ApiCallDriver - Response body: {"errorMessage":"Could not find Profile Set '3'"}
10:58:05.205 [main] ERROR com.delphix.masking.initializer.maskingApi.SetupDriver - Got status code: [404] with message [Could not find Profile Set '3']

**Comment by bpg130** [comment]
@slusardi01 Did you remove the profiler sets/expressions from the `BASE.json` when you edited it? Given that you created the backup with the `-g` flag, they should have been included and they should have been imported prior creating the profile job.

**Comment by slusardi01** [comment]
No, I did remove the profile set/expressions from the BASE.json file as we wanted that profiler set to come over.   My thinking is that the profile set that existed on Engine 2 had an internal ID number that may be in conflict with the one we were trying to bring over from Engine 1.

**Comment by bpg130** [comment]
Thanks, @slusardi01, I see the issue now. This should be fixed in the next version that will hopefully be released later this week.

**Comment by slusardi01** [comment]
Is this 5.2.5 ?

**Comment by bpg130** [comment]
Ahh no, sorry for the confusion. I meant the next release of this tool, not the masking application itself.

**Comment by slusardi01** [comment]
Okay, so this will be release 2 of the masking initializer, correct  (not the API) ?

**Comment by bpg130** [comment]
Yes, this will be fixed in the next release of this initializer tool (coming this week). There is no bug in the actual API.

**Comment by slusardi01** [comment]
ok
