### ISSUE TITLE
Modified Profiler was not updated on Import

### ISSUE THREAD

**Issue by dschumac** [delphix/masking-initializer#6]
Ran an export on our lab engine where the Payx N2D Profile Set had been updated removing a Data Check and then ran an import into one of our Prod engines which finished successfully but when we checked the existing Profile Set, it did not have the changes to it. We can see the changes to the Profile Set in the json file:
  "profileSetId": 7,
      "profileSetName": "Payx N2D",
      "createdBy": "slusardi",
      "createdTime": "2018-04-05T19:15:18.140+0000",
      "description": false,
      "profileExpressionNames": [
        "Credit Card Number",
        "Payx Social Security Nbr",
        "PX_SSN_SUFFIX",
        "Beneficiary ID",
        "Birth Date",
        "Payx PIN Nbr",
        "Payx Password",
        "PAYX SSN",
        "Drivers License Number",
        "Payx Drivers License",
        "Birth Date2",
        "Beneficiary Number",
        "Card Number",
        "Payx Tax ID Nbr",
        "Birth Date1",
        "Payx TIN",
        "Security Code",
        "Drivers License Number1",
        "Payx US Passport"

But when we log into the engine where the import ran that Profile Set is not updated:
![image](https://user-images.githubusercontent.com/39305036/40060154-f1a18c2a-5823-11e8-9fb9-82341fd13361.png)

The 2 expressions that start with DATA are still there but are not in the json file.
This is the import command I ran:
dlpx-masking-initializer -f  testlab -H delappdmh3 -p 8282 -u delphixAPI -P D3lphixAp! -s -l DEBUG 
And here are the last few output lines:
09:24:11.341 [main] INFO  com.delphix.masking.initializer.maskingApi.endpointCal
ler.ApiCallDriver - http://delappdmh3:8282/masking/api/profile-jobs POST
09:24:11.341 [main] DEBUG com.delphix.masking.initializer.maskingApi.endpointCal
ler.ApiCallDriver - Body: {
  "profileJobId": 94,
  "jobName": "BENDB-Profile-HSA",
  "profileSetId": 3,
  "rulesetId": 10,
  "createdBy": "delphix_admin",
  "createdTime": "2018-01-17T19:51:03.178+0000",
  "email": "slusardi@paychex.com",
  "feedbackSize": 50000,
  "jobDescription": "",
  "maxMemory": 16382,
  "minMemory": 16382,
  "multiTenant": true,
  "numInputStreams": 20
}
09:24:11.405 [main] DEBUG com.delphix.masking.initializer.maskingApi.endpointCal
ler.ApiCallDriver - Response body: {"profileJobId":8,"jobName":"BENDB-Profile-HS
A","profileSetId":3,"rulesetId":10,"createdBy":"delphixAPI","createdTime":"2018-
05-15T13:24:12.192+0000","email":"slusardi@paychex.com","feedbackSize":50000,"jo
bDescription":"","maxMemory":16382,"minMemory":16382,"multiTenant":true,"numInpu
tStreams":20}
c:\delphix\dlpx-masking-initializer\bin>

**Comment by dschumac** [comment]
The following command worked, bringing in the updated Profile Set

**Comment by dschumac** [comment]
dlpx-masking-initializer -f  testlab -H delappdmh3 -p 8282 -u delphixAPI -P D3lphixAp! -s -r

**Comment by bpg130** [comment]
@dschumac yes, you must specify the `-r` flag if you wish to overwrite existing objects on a masking application. Closing this as this as it is not an issue.
