### ISSUE TITLE
Missing Algorithm (Sync###) JSON files on backup 

### ISSUE THREAD

**Issue by slusardi01** [delphix/masking-initializer#7]
When we have 37 algorithms and 2 mapplets on engine #1.   Five of those 37 algorithms were created by us, the others are owner 'System'.  When we look at the backup folder for sync###.json files we only have 32 (only 31 of which are algorithms as the first is the encryption key).   We are missing json files for the 6 "maplets" shown in the algorithm GUI with type "DEFAULT" as well as two of the five algorithms we created.

Of the five algorithms we created, the three that had files produced were of type SM and Binary SL.  The two that did not generate json files were of type MM and BW.

**Comment by bpg130** [comment]
The masking application does not currently support exporting min-max (MM) or free text redaction (BW) algorithms. That means that this tool cannot manage those types as there is no way to access them through the API.

The same is true for the `DEFAULT` algorithms. They are the same on every engine, and we do not support managing them through the masking application API in the 5.2 release.
